feat: add theme-ui-react18 example
remix-run/examples pull request #145
Opened 2023-01-31 18:12 UTC by khairold

The current example of Theme UI is on React 17.
It doesn't work with React 18.

I'd like to contribute an example of implementing Theme UI on Remix with React 18.

2023-01-31 22:47 UTC, MichaelDeBoey requested changes
Please update the existing example instead of creating a separate React 18 version of it 🙏

2023-02-01 05:50 UTC, khairold commented
> Please update the existing example instead of creating a separate React 18 version of it 🙏

Updated

2023-02-01 06:21 UTC, machour requested changes

2023-02-01 06:21 UTC, machour commented on theme-ui/README.md
> +[![Open in CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/remix-run/examples/tree/main/theme-ui-react18)
```suggestion
[![Open in CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/remix-run/examples/tree/main/theme-ui)
```

2023-02-01 06:21 UTC, machour commented on theme-ui/README.md
> +<!-- TODO: update this link to the path for your example: -->
```suggestion
```

2023-02-01 06:21 UTC, machour commented on theme-ui/README.md
> +# Example of Remix (React 18) with Theme UI
```suggestion
# Example with Theme UI
```

2023-02-01 14:43 UTC, khairold commented
Fixed lint error and warning

2023-02-02 10:28 UTC, khairold commented
Hi this is my first pull request so I'm not sure of the process. 
Just want to check if there is anything else pending on my side.

2023-04-17 20:08 UTC, closed without merging