Fix(mantine): fix build error
remix-run/examples pull request #149
Opened 2023-02-07 00:49 UTC by ikorecky

Fixes issue #117 at https://github.com/remix-run/examples/issues/117.
Following the guidelines at https://mantine.dev/guides/remix/.
It addresses the limitation noted in the guide, "Mantine is based on [emotion] which currently does not support [renderToPipeableStream], default Remix boilerplate will not support Mantine"
![image](https://user-images.githubusercontent.com/8957890/217117896-47a16d67-a704-47ce-b7cf-ebf769bf1bf9.png)

2023-03-21 12:02 UTC, MichaelDeBoey commented
@ikorecky Can you please rebase your branch onto latest `main` & resolve conflicts?

2023-03-22 00:13 UTC, MichaelDeBoey requested changes
We're apparently also missing some changes in `entry.client.tsx` (which needs to be added again in that case)

2023-03-22 01:50 UTC, ikorecky commented on mantine/app/root.tsx
This example is slightly different from the Mantine guide.
We use the `MantineProvider` in the `MantineTheme` component to set the theme for our application.
The `theme` prop gets the `colorScheme` value by the toggle changes.
This is necessary because the `colorScheme` value is used to determine the color scheme of the application.
What do you think?

2023-04-27 14:14 UTC, MichaelDeBoey requested changes

2023-04-27 14:14 UTC, MichaelDeBoey commented on .history/mantine/app/entry.server_20230427120314.tsx
We should remove the `.history` folder?

2023-05-14 13:25 UTC, MichaelDeBoey requested changes

2023-05-14 13:25 UTC, MichaelDeBoey commented on mantine/app/entry.client.tsx
> +  });
```suggestion
startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <ClientProvider>
        <RemixBrowser />
      </ClientProvider>
    </StrictMode>
  );
```

2023-05-14 13:25 UTC, MichaelDeBoey commented on mantine/app/entry.client.tsx
> +}
```suggestion
```

2023-05-15 20:40 UTC, MichaelDeBoey requested changes

2023-05-15 20:40 UTC, MichaelDeBoey commented on mantine/app/entry.client.tsx
> +  );
```suggestion
  );
});
```

2023-05-15 22:03 UTC, MichaelDeBoey approved these changes

2023-05-31 14:24 UTC, merged