feat: update `twind` example
remix-run/examples pull request #178
Opened 2023-03-21 09:38 UTC by Palbahngmiyine

Existing twind examples use the deprecated twind library. 
So this pr is update example to @twind/core instead of the no longer maintained twind build.

The updated example was modified by referring to the [example page in twind repository](https://github.com/tw-in-js/twind/tree/main/examples/with-remix_react-v18).

2023-03-21 11:37 UTC, MichaelDeBoey requested changes

2023-03-21 11:37 UTC, MichaelDeBoey commented on twind/app/entry.client.tsx
> +import './twind';
Could we keep this in `root` as it was before?

2023-03-21 11:37 UTC, MichaelDeBoey commented on twind/app/entry.server.tsx
This file can now be removed entirely, as we're not doing anything custom anymore (see #159)

2023-03-21 16:07 UTC, Palbahngmiyine commented
Hello, @MichaelDeBoey! i I checked the adjustments your sugesstion and update it! However, in the current twind example, the actual example does not work due to a bug caused by hydration mismatch.

This seems to have been resolved in the [next react version(18.3.0)](https://github.com/facebook/react/issues/24430#issuecomment-1440427646), and when tested with the actual react@next, react-dom@next version, i found that it actually worked.

Therefore, I think it would be good to freeze this PR and merge it when the react version is updated.

2023-03-23 06:50 UTC, Palbahngmiyine commented
@MichaelDeBoey 

It was my mistake, the original PR(without suggestions) was also found to be not working, I can change it to work with a slight fix (entry.client.tsx, entry.server.tsx needed) though.

Apart from that, existing examples(current main branch) do not work properly, so I suggest a direction to open and modify a new PR with a working example implementation that adds entry.client.tsx, entry.server.tsx instead of the current PR.

If you agree with the suggestion, I'll be able to work immediately, and below is the error stacktrace of the existing example(current main branch). 

![stacktrace](https://user-images.githubusercontent.com/15980437/227125301-94fb7cc5-bf7e-459c-920d-a108816abb4b.png)

2023-03-23 21:33 UTC, MichaelDeBoey commented
@Palbahngmiyine You can (force) push your changes in this PR as well if you want

2023-03-25 02:39 UTC, Palbahngmiyine commented
@MichaelDeBoey 

Thank you for your kind comment, and as I mentioned before, I fixed an issue where the existing example didn't work correctly.

When the react version is updated, I'll create a new PR reflecting what is mentioned in #159 .

Thank you!

2023-06-06 21:43 UTC, MichaelDeBoey commented
Hi @Palbahngmiyine!

Are you still interested in getting this one merged?

If so, please rebase onto latest `main` & fix conflicts

2023-06-07 15:23 UTC, Palbahngmiyine commented
Hello, @MichaelDeBoey !

I hope this PR will be merged and I fixed the conflict with the main branch 😊.

2023-06-07 18:41 UTC, MichaelDeBoey requested changes

2023-06-07 18:41 UTC, MichaelDeBoey commented on twind/app/entry.client.tsx
> +install(config);
Please put this in `root.tsx` again

2023-06-07 18:41 UTC, MichaelDeBoey commented on twind/app/entry.server.tsx
> -export default handleRequest;
Please keep this as it was and only update the actual needed changes

2023-06-23 06:34 UTC, closed without merging

2023-06-23 06:38 UTC, Palbahngmiyine commented
Sorry, I closed PR due to IDE settings while resolving the latest main branch conflict. I will revise it again to reflect your review!