feat: add primereact example
remix-run/examples pull request #194
Opened 2023-03-29 18:31 UTC by kendallcamposs

2023-03-30 11:52 UTC, MichaelDeBoey requested changes
Please update this example to start from the `__template` folder & add the rest of your example code afterwards

2023-04-17 21:56 UTC, MichaelDeBoey requested changes

2023-04-17 21:56 UTC, MichaelDeBoey commented on primereact/README.md
> +[![Open in codesandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/frosty-christian-7yu236?file=%2FREADME.md)
```suggestion
[![Open in CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/remix-run/examples/tree/main/primereact)
```

2023-04-17 21:56 UTC, MichaelDeBoey commented on primereact/app/entry.client.tsx
Please remove this file

2023-04-17 21:56 UTC, MichaelDeBoey commented on primereact/app/entry.server.tsx
Please remove this file

2024-05-29 22:41 UTC, machour commented
Hey @kendallcamposs 👋🏼 
Is this ready for review or still a work in progress?

2024-06-09 00:24 UTC, kendallcamposs commented
Hi @machour!

I think we should close it because of this issue: https://github.com/primefaces/primereact/issues/4675

2024-06-09 06:36 UTC, closed without merging

2024-07-24 19:10 UTC, AfzalSabbir commented
Stuck here as well.
As it's a dead end, and my project is in a begine stage. I'm going to move to something else.