Mux Video example
remix-run/examples pull request #441
Opened 2024-03-08 14:35 UTC by decepulis

Ahoy! Adding a [Mux Video](https://www.mux.com) example following a basic UGC upload workflow. You can see a similar flow implemented at https://stream.new.

Looking forward to any feedback, and looking forward to getting this example into the hands of Remix devs!

2024-05-29 19:40 UTC, machour requested changes
Hey 👋 

Thank you so much for the contribution and sorry for the delays getting back to you. 

I'd like to get this example merged, but I wonder if you could: 
- upgrade the template to the Vite version (see the updated __template folder) 
- remove tailwindcss usage (to keep the example minimalistic) 
- drop the pricing part from the README, as a user interested in Mux will get all that info from the official website

Let me know if you have thoughts about this 🙏

2024-05-30 14:17 UTC, decepulis commented
Hey @machour! Thanks for the feedback. It's addressed.

2024-05-30 14:29 UTC, decepulis commented
Ah linting errors. Taking a look...

2024-05-30 14:42 UTC, machour approved these changes
Neat work, thank you!

Just two little details in the README and we're good to go!

By the way, tested the example locally, uploaded a video, and when it was done, I had an error flash before the video got rendered. Are you getting the same thing? (I'll suspect my local env otherwise)

![Screenshot 2024-05-30 at 3 38 30 PM](https://github.com/remix-run/examples/assets/304450/e15a6c17-b779-4ff4-b23f-3d241d21adab)

2024-05-30 14:42 UTC, machour commented on mux-video/README.md
> +npx create-remix@latest --template examples/mux-video
```suggestion
npx create-remix@latest --template remix-run/examples/mux-video
```

2024-05-30 14:42 UTC, machour commented on mux-video/README.md
> +Then, go to the [settings page](https://dashboard.mux.com/settings/access-tokens) in your Mux dashboard, get a new **API Access Token**. Use that token to set the variables in `.env.local`:
Can you specify the permissions needed ? (I ticked everything 😅 )

2024-05-30 14:59 UTC, decepulis commented
I'm seeing the same rule of hooks error. But only the first time we run into that page, and only if that page isn't the first page I visit on boot. Similarly, if the first page I visit is the `playback` page, `mux-player-react` loads fine but `mux-uploader-react` throws a rule of hooks error. The errors go away after I _hard_ reload the page, clearing the browser cache. The errors re-appear if I clear my `node_modules` and start again.

I wonder if it's related to `[vite] ✨ new dependencies optimized: @mux/mux-player-react`; I only notice the error before that happens.

I don't know enough about vite or how it optimizes dependencies to be sure, though. Do you?

2024-05-30 15:10 UTC, merged