feat(firebase): add Google Account auth
remix-run/examples pull request #52
Opened 2022-10-31 12:54 UTC by penx

Reopening https://github.com/remix-run/examples/pull/4, https://github.com/remix-run/remix/pull/4057 against remix-run/examples

Firebase example - Integration with Google Sign-in Provider

Closes: "sign-in with Google" suggestion at https://github.com/remix-run/remix/pull/1811#issuecomment-1050238130

Adds a "Login with Google" link:

> <img width="179" alt="Screenshot 2022-08-24 at 15 16 57" src="https://user-images.githubusercontent.com/1027024/186442693-e4862675-dfbb-498d-8a66-bda1da3f1fc0.png">

...that takes a user to the Google's auth screen:

> <img width="520" alt="Screenshot 2022-08-24 at 15 17 22" src="https://user-images.githubusercontent.com/1027024/186442810-dd58d3b8-785c-40d3-b8be-48a77b4df417.png">

 ...and then creates an account (if it doesn't yet exist) and signs them in:

> <img width="253" alt="Screenshot 2022-08-24 at 15 19 26" src="https://user-images.githubusercontent.com/1027024/186442912-18af6e25-8609-4111-b627-1ad08b531388.png">

2023-01-20 13:13 UTC, penx commented
@machour @mcansh @MichaelDeBoey 

happy to abandon this if it's not wanted, but I've opened this PR 3 times now, and rebased several times on request, now github actions is telling me you're waiting for a response from me 😄

2023-01-20 14:27 UTC, MichaelDeBoey requested changes
@penx Please rebase this branch onto latest `dev` & resolve conflicts and remarks

2023-01-20 14:27 UTC, MichaelDeBoey commented on firebase/app/routes/auth/google.tsx
> +export const loader: LoaderFunction = async ({ request }) => {
```suggestion
export const loader = async ({ request }: LoaderArgs) => {
```

2023-01-20 14:27 UTC, MichaelDeBoey commented on firebase/app/routes/auth/google.tsx
> +import type { LoaderFunction } from "@remix-run/node";
```suggestion
import type { LoaderArgs } from "@remix-run/node";
```

2023-01-25 16:43 UTC, penx commented
@MichaelDeBoey rebased and confirmed it's all still working. Also addressed feedback and updated the docs a little.

2023-01-25 16:46 UTC, penx commented on firebase/README.md
> +To run this example, you either need to create a firebase proejct or use the emulators:
```suggestion
To run this example, you either need to create a firebase project or use the emulators:
```
```suggestion
To run this example, you either need to create a firebase proejct or use the emulators:
```

2023-01-25 16:48 UTC, penx commented on firebase/app/routes/login.tsx
> +      </p>
Could perhaps hide this if GOOGLE_CLIENT_ID is not set

2023-01-25 16:49 UTC, penx commented on firebase/app/routes/auth/google.tsx
> +      redirect_uri: "http://localhost:3000/auth/google",
I don't remember why this was hard coded to localhost. Perhaps something is needed here. Will need to test a deployed version.

2023-01-25 16:50 UTC, penx commented on firebase/app/routes/auth/google.tsx
> +      redirect_uri: "http://localhost:3000/auth/google",
confirmed this is an issue - using firebase functions locally (:5002) will redirect to :3000

2023-01-25 16:51 UTC, penx commented on firebase/app/routes/login.tsx
> +&redirect_uri=http://localhost:3000/auth/google\
also need to address hard coded localhost url here

2023-01-25 16:51 UTC, MichaelDeBoey requested changes

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
> +To run this example, you either need to create a firebase proejct or use the emulators:
```suggestion
To run this example, you either need to create a Firebase project or use [the emulators](https://firebase.google.com/docs/emulator-suite):
```

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
> +To run this example, you either need to create a Firebase project or use the emulators:
```suggestion
To run this example, you either need to create a Firebase project or use [the emulators](https://firebase.google.com/docs/emulator-suite):
```

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
>  ### 1. Run against a Firebase Project
```suggestion
### 1. Run against a Firebase project
```

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
> +1. [Create a Firebase Project](https://console.firebase.google.com).
```suggestion
1. [Create a Firebase project](https://console.firebase.google.com).
```

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
> +2. Enable Auth (with email) and Firestore.
```suggestion
2. Enable [Auth](https://firebase.google.com/docs/auth) (with email) and [Cloud Firestore](https://firebase.google.com/docs/firestore).
```

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
> +5. Set the API_KEY value to the [Web API Key](https://firebase.google.com/docs/reference/rest/auth), which can be obtained on the project settings page in your Firebase admin console.
```suggestion
5. Set the `API_KEY` value to the [Web API Key](https://firebase.google.com/docs/reference/rest/auth), which can be obtained on the project settings page in your Firebase admin console.
```

2023-01-25 16:51 UTC, MichaelDeBoey commented on firebase/README.md
> +6. Set SERVICE_ACCOUNT to the contents of your service account's private key JSON file:
```suggestion
6. Set `SERVICE_ACCOUNT` to the contents of your service account's private key JSON file:
```

2023-04-16 18:11 UTC, penx commented
@MichaelDeBoey not sure why this was closed. Are you waiting for something from?

2023-04-16 18:23 UTC, penx commented
Actually maybe it’s the hard coded localhost, had forgotten this needed addressing

2023-04-16 19:09 UTC, MichaelDeBoey commented
@penx This was indeed waiting for the hardcoded `localhost` I think

I'll re-open as I know we'll see the update in a timely manner. 😉

I'll also update the `no-response` workflow to give a notice before actually closing the PRs 👍

2023-05-03 10:49 UTC, penx commented
I have removed the 2 hard coded "localhost", and calculate redirectUri instead

2023-05-06 22:29 UTC, MichaelDeBoey requested changes
Some small remarks

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/README.md
>  1. Follow the "Run against a Firebase Project" steps above if not done already
```suggestion
1. Follow the "Run against a Firebase project" steps above if not done already
```

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/README.md
> +The "Login with Google" link will only work when running against a Firebase Project.
```suggestion
The "Login with Google" link will only work when running against a Firebase project.
```

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/README.md
> +After the steps in "Run against a Firebase Project" have been completed:
```suggestion
After the steps in "Run against a Firebase project" have been completed:
```

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/README.md
> +- In the [Firebase Console](https://console.firebase.google.com), navigate to Authentication > Sign-in method > Add new provider > Google. Make a note of the client ID and secret and add them to the
```suggestion
- In the [Firebase Console](https://console.firebase.google.com), navigate to Authentication > Sign-in method > Add new provider > Google. Make a note of the client ID and secret and add them to the `.env` file as `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`.
```

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/app/firebase-rest.ts
> +    postBody: "id_token=" + idToken + "&providerId=" + providerId,
```suggestion
    postBody: `id_token=${idToken}&providerId=${providerId}`,
```

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/app/firebase-rest.ts
> +    requestUri: "http://localhost",
@penx Should this stay `localhost`? 🤔

2023-05-06 22:29 UTC, MichaelDeBoey commented on firebase/app/routes/login.tsx
> +  useLocation,
```suggestion
```

2023-05-27 23:07 UTC, closed without merging