docs: enhance the contributing docs, and clean up README
remix-run/examples pull request #8
Opened 2022-09-17 08:11 UTC by machour

I expanded the contributing guide for this particular repo in `CONTRIBUTING.md`, since this might be a first OSS contribution for some.

Also refreshed the README a bit

2022-09-17 09:15 UTC, machour commented on README.md
> +npx create-remix@latest --template examples/<example-dir>
This will work again when https://github.com/remix-run/remix/pull/4208 is merged

2022-09-17 13:21 UTC, MichaelDeBoey requested changes

2022-09-17 13:21 UTC, MichaelDeBoey commented on CONTRIBUTING.md
> +git commit -m "Add an example for <REPLACE ME>"
```suggestion
git commit -m "feat: add `<FOLDER-NAME>` example"
```

2022-09-17 13:21 UTC, MichaelDeBoey commented on CONTRIBUTING.md
> +7. You're done, thank you! :tada:
```suggestion
7. You're done, thank you! 🎉
```

2022-09-17 13:21 UTC, MichaelDeBoey commented on README.md
> +Please see [our guide to contributing](CONTRIBUTING.md).
```suggestion
Please see [our contribution guide](CONTRIBUTING.md).
```

2022-09-17 17:22 UTC, MichaelDeBoey approved these changes

2022-09-26 20:55 UTC, chaance approved these changes
Great edits, thank you!

2022-09-26 20:55 UTC, merged